<?php
session_start();
require_once '../../includes/auth.php';

date_default_timezone_set('Asia/Manila');

$currentMonthName = date('F');
$currentYear = date('Y');
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Documents & Images</title>
  <link rel="icon" type="image/png" href="../../assets/img/logo.png">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  <link rel="stylesheet" href="../../assets/css/layout.css">
  <link rel="stylesheet" href="../../assets/css/document.css?v=1.1">
</head>
<body>
  <?php include_once '../../layouts/sidebar_admin.php'; ?>
  <div class="main-content">
    <?php include_once '../../layouts/header.php'; ?>
    <div class="container mt-4 px-4">
      <h2 class="page-title mb-3">Documents & Images</h2>
      <div class="document-container">
        <!-- CONTROLS -->
        <div class="document-controls">
          <div class="filter-group">
            <select class="form-select filter-input">
              <option value="">Filter by Document Type</option>
              <option>Tax Declaration</option>
              <option>Deed of Sale</option>
              <option>Survey Plan</option>
              <option>Land Title</option>
              <option>Property Image</option>
            </select>
            <select class="form-select filter-input">
              <option value="">Filter by Barangay</option>
              <option>Poblacion</option>
              <option>San Jose</option>
              <option>San Roque</option>
            </select>
          </div>
          <div class="search-group">
            <div class="input-group search-box">
              <span class="input-group-text">
                <i class="bi bi-search"></i>
              </span>
              <input type="text" class="form-control search-input" placeholder="Search property or owner...">
            </div>
          </div>
        </div>
        <!-- TABLE -->
        <div class="table-responsive mt-3">
          <table class="table table-striped document-table">
            <thead>
              <tr>
                <th>Document ID</th>
                <th>Reference No</th>
                <th>Property ID</th>
                <th>Owner ID</th>
                <th>Document Type</th>
                <th>File Path</th>
                <th>Date Issued</th>
                <th>Generated By</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td colspan="9" class="text-center text-muted py-2">No documents found.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
